config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :payments
  root "payments#new"
  get "payments/success"
  get "payments/cancel"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @user = user
    product = Stripe::Product.retrieve('prod_QCCrNXeyMcBLdS')
    price = Stripe::Price.retrieve(product.default_price)
    @currency = price.currency == 'usd' ? '$' : nil
    @price = price.unit_amount
  end
  
  def create
    current_user = user

    #create stripe customer for payment, update if already created
    customer = Stripe::Customer.create({
      name: current_user.full_name,
      :email => params[:stripeEmail],
      description: "Customer id: #{current_user.id}",
      :source => params[:stripeToken]
    })

    Stripe::Subscription.create({
      customer: customer,
      items: [{price: ENV["STRIPE_SUBSCRIPTION_ID"]}],
    })
    redirect_to root_url, notice: "Purchase Successful"

  end

  def user
    OpenStruct.new(
      id: 173,
      full_name: 'Juancito de los palotes',
      email: 'juandev@gmail.com'
    )
  end

  def success
    #handle successful payments
    redirect_to root_url, notice: "Purchase Successful"
  end

  def cancel
    #handle if the payment is cancelled
    redirect_to root_url, notice: "Purchase Unsuccessful"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleStripe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<%= form_tag payments_path do %>
  <label class="amount">
      <span>Subscription: <%= @currency %><%= @price.to_f / 100 %></span>
  </label>

  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-email="<%= @user.email %>"
    data-amount="<%= @price %>"
    data-locale="auto">
  </script>
<% end %>